// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'dependency_container_test.dart' as prefix1;
import 'package:resolve_di/src/reflector.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl(
        r'A',
        r'.A',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[0],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix1.A() : null,
        },
        -1,
        0,
        const <int>[],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'InterfaceA',
        r'.InterfaceA',
        134218247,
        1,
        const prefix0.Reflector(),
        const <int>[1],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        -1,
        1,
        const <int>[],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'B',
        r'.B',
        134217735,
        2,
        const prefix0.Reflector(),
        const <int>[2],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix1.B() : null,
        },
        -1,
        2,
        const <int>[1],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'C',
        r'.C',
        134217735,
        3,
        const prefix0.Reflector(),
        const <int>[3],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix1.C() : null,
        },
        -1,
        3,
        const <int>[1],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'NamedDependency',
        r'.NamedDependency',
        134217735,
        4,
        const prefix0.Reflector(),
        const <int>[4],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix1.NamedDependency() : null,
        },
        -1,
        4,
        const <int>[],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'NamedConsumer',
        r'.NamedConsumer',
        134217735,
        5,
        const prefix0.Reflector(),
        const <int>[5],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              ({dependency}) =>
                  b ? prefix1.NamedConsumer(dependency: dependency) : null,
        },
        -1,
        5,
        const <int>[],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.MethodMirrorImpl(
        r'',
        64,
        0,
        -1,
        0,
        0,
        const <int>[],
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        64,
        1,
        -1,
        1,
        1,
        const <int>[],
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        64,
        2,
        -1,
        2,
        2,
        const <int>[],
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        64,
        3,
        -1,
        3,
        3,
        const <int>[],
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        64,
        4,
        -1,
        4,
        4,
        const <int>[],
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        0,
        5,
        -1,
        5,
        5,
        const <int>[],
        const <int>[0],
        const prefix0.Reflector(),
        null,
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'dependency',
        134358022,
        5,
        const prefix0.Reflector(),
        4,
        4,
        4,
        const <int>[],
        null,
        null,
        #dependency,
      ),
    ],
    <Type>[
      prefix1.A,
      prefix1.InterfaceA,
      prefix1.B,
      prefix1.C,
      prefix1.NamedDependency,
      prefix1.NamedConsumer,
    ],
    6,
    {},
    {},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
