// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'package:mvvm_reflection/features/counter/data/repositories/counter_repository_impl.dart'
    as prefix1;
import 'package:mvvm_reflection/features/counter/domain/repositories/counter_repository.dart'
    as prefix2;
import 'package:mvvm_reflection/features/counter/domain/usecases/increment_counter_use_case.dart'
    as prefix5;
import 'package:mvvm_reflection/features/counter/presentation/view/counter_page.dart'
    as prefix3;
import 'package:mvvm_reflection/features/counter/presentation/view_models/counter_view_model.dart'
    as prefix4;
import 'package:resolve_di/src/reflector.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl(
        r'CounterRepositoryImpl',
        r'.CounterRepositoryImpl',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[0],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix1.CounterRepositoryImpl() : null,
        },
        -1,
        0,
        const <int>[1],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'CounterRepository',
        r'.CounterRepository',
        134218247,
        1,
        const prefix0.Reflector(),
        const <int>[1],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        -1,
        1,
        const <int>[],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'CounterPage',
        r'.CounterPage',
        134217735,
        2,
        const prefix0.Reflector(),
        const <int>[2],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              ({viewModel}) =>
                  b ? prefix3.CounterPage(viewModel: viewModel) : null,
        },
        -1,
        2,
        const <int>[],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'CounterViewModel',
        r'.CounterViewModel',
        134217735,
        3,
        const prefix0.Reflector(),
        const <int>[3],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              ({incrementCounterUseCase}) => b
              ? prefix4.CounterViewModel(
                  incrementCounterUseCase: incrementCounterUseCase,
                )
              : null,
        },
        -1,
        3,
        const <int>[],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'IncrementCounterUseCase',
        r'.IncrementCounterUseCase',
        134217735,
        4,
        const prefix0.Reflector(),
        const <int>[4],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              (_counterRepository) => b
              ? prefix5.IncrementCounterUseCase(_counterRepository)
              : null,
        },
        -1,
        4,
        const <int>[],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.MethodMirrorImpl(
        r'',
        64,
        0,
        -1,
        0,
        0,
        const <int>[],
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        64,
        1,
        -1,
        1,
        1,
        const <int>[],
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        128,
        2,
        -1,
        2,
        2,
        const <int>[],
        const <int>[0],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        0,
        3,
        -1,
        3,
        3,
        const <int>[],
        const <int>[1],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        0,
        4,
        -1,
        4,
        4,
        const <int>[],
        const <int>[2],
        const prefix0.Reflector(),
        null,
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'viewModel',
        134358022,
        2,
        const prefix0.Reflector(),
        3,
        3,
        3,
        const <int>[],
        null,
        null,
        #viewModel,
      ),
      r.ParameterMirrorImpl(
        r'incrementCounterUseCase',
        134356998,
        3,
        const prefix0.Reflector(),
        4,
        4,
        4,
        const <int>[],
        null,
        null,
        #incrementCounterUseCase,
      ),
      r.ParameterMirrorImpl(
        r'_counterRepository',
        134349862,
        4,
        const prefix0.Reflector(),
        1,
        1,
        1,
        const <int>[],
        null,
        null,
        null,
      ),
    ],
    <Type>[
      prefix1.CounterRepositoryImpl,
      prefix2.CounterRepository,
      prefix3.CounterPage,
      prefix4.CounterViewModel,
      prefix5.IncrementCounterUseCase,
    ],
    5,
    {},
    {},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
