// Mocks generated by Mockito 5.4.6 from annotations
// in mvvm_reflection/test/features/counter/presentation/view_models/counter_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:mvvm_reflection/features/counter/domain/usecases/increment_counter_use_case.dart'
    as _i2;
import 'package:mvvm_reflection/utils/result.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IncrementCounterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncrementCounterUseCase extends _i1.Mock
    implements _i2.IncrementCounterUseCase {
  @override
  _i3.Result<int> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.dummyValue<_i3.Result<int>>(
              this,
              Invocation.method(#execute, []),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.Result<int>>(
              this,
              Invocation.method(#execute, []),
            ),
          )
          as _i3.Result<int>);
}
