// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'dart:ui' as prefix5;
import 'package:command_it/command_it.dart' as prefix3;
import 'package:meta/meta.dart' as prefix2;
import 'package:mvvm_reflection/app/reflector.dart' as prefix0;
import 'package:mvvm_reflection/features/counter/domain/usecases/increment_counter_use_case.dart'
    as prefix4;
import 'package:mvvm_reflection/features/counter/presentation/view_models/counter_view_model.dart'
    as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.AppReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl(
        r'CounterViewModel',
        r'.CounterViewModel',
        134217735,
        0,
        const prefix0.AppReflector(),
        const <int>[0, 1, 3, 4],
        const <int>[5, 6, 7, 8, 9, 10, 11, 1, 12, 13, 2, 3],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              ({incrementCounterUseCase}) => b
              ? prefix1.CounterViewModel(
                  incrementCounterUseCase: incrementCounterUseCase,
                )
              : null,
        },
        -1,
        -1,
        const <int>[-1],
        const <Object>[prefix0.appReflector],
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.VariableMirrorImpl(
        r'incrementCommand',
        151127045,
        0,
        const prefix0.AppReflector(),
        -1,
        1,
        2,
        null,
        const [],
      ),
      r.MethodMirrorImpl(
        r'dispose',
        1310722,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.AppReflector(),
        const <Object>[override],
      ),
      r.ImplicitGetterMirrorImpl(const prefix0.AppReflector(), 0, 2),
      r.MethodMirrorImpl(
        r'count',
        2097155,
        0,
        -1,
        3,
        3,
        null,
        const <int>[],
        const prefix0.AppReflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'',
        0,
        0,
        -1,
        0,
        0,
        null,
        const <int>[0],
        const prefix0.AppReflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'==',
        2097154,
        -1,
        -1,
        4,
        4,
        null,
        const <int>[1],
        const prefix0.AppReflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'toString',
        2097154,
        -1,
        -1,
        5,
        5,
        null,
        const <int>[],
        const prefix0.AppReflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'noSuchMethod',
        524290,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[2],
        const prefix0.AppReflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'hashCode',
        2097155,
        -1,
        -1,
        3,
        3,
        null,
        const <int>[],
        const prefix0.AppReflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'runtimeType',
        2097155,
        -1,
        -1,
        6,
        6,
        null,
        const <int>[],
        const prefix0.AppReflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'addListener',
        1310722,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[3],
        const prefix0.AppReflector(),
        const <Object>[override],
      ),
      r.MethodMirrorImpl(
        r'removeListener',
        1310722,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[4],
        const prefix0.AppReflector(),
        const <Object>[override],
      ),
      r.MethodMirrorImpl(
        r'notifyListeners',
        1310722,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.AppReflector(),
        const <Object>[
          prefix2.protected,
          prefix2.visibleForTesting,
          const pragma('vm:notify-debugger-on-exception'),
        ],
      ),
      r.MethodMirrorImpl(
        r'hasListeners',
        2097155,
        -1,
        -1,
        4,
        4,
        null,
        const <int>[],
        const prefix0.AppReflector(),
        const <Object>[prefix2.protected],
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'incrementCounterUseCase',
        134356998,
        4,
        const prefix0.AppReflector(),
        -1,
        7,
        7,
        null,
        const [],
        null,
        #incrementCounterUseCase,
      ),
      r.ParameterMirrorImpl(
        r'other',
        134348806,
        5,
        const prefix0.AppReflector(),
        -1,
        8,
        8,
        null,
        const [],
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'invocation',
        134348806,
        7,
        const prefix0.AppReflector(),
        -1,
        9,
        9,
        null,
        const [],
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'listener',
        134217734,
        10,
        const prefix0.AppReflector(),
        -1,
        10,
        10,
        null,
        const [],
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'listener',
        134217734,
        11,
        const prefix0.AppReflector(),
        -1,
        10,
        10,
        null,
        const [],
        null,
        null,
      ),
    ],
    <Type>[
      prefix1.CounterViewModel,
      const m.TypeValue<prefix3.Command<void, void>>().type,
      prefix3.Command,
      int,
      bool,
      String,
      Type,
      prefix4.IncrementCounterUseCase,
      Object,
      Invocation,
      prefix5.VoidCallback,
    ],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'addListener': (dynamic instance) => instance.addListener,
      r'removeListener': (dynamic instance) => instance.removeListener,
      r'dispose': (dynamic instance) => instance.dispose,
      r'notifyListeners': (dynamic instance) => instance.notifyListeners,
      r'hasListeners': (dynamic instance) => instance.hasListeners,
      r'incrementCommand': (dynamic instance) => instance.incrementCommand,
      r'count': (dynamic instance) => instance.count,
    },
    {},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
